pipeline {
    agent {
        docker { image "vnstat/tools" }
    }
    triggers {
        upstream 'Stage_from_GitHub'
    }
    stages {
        stage('Clean') {
            steps {
                sh 'rm -fr vnstat* *.txt *.xml'
            }
        }
        stage('Get') {
            steps {
                copyArtifacts(projectName: 'Stage_from_GitHub', filter: 'vnstat.tar.gz', selector: lastSuccessful())
                sh 'sha256sum vnstat.tar.gz >fingerprint.txt'
                sh 'tar zxvf vnstat.tar.gz'
                sh 'mv -v vnstat-* vnstat'
            }
        }
        stage('Typos') {
            steps {
                dir('vnstat') {
                    sh '''
                        typos --files man examples cfg CHANGES INSTALL* README* U*
                    '''
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'fingerprint.txt, buildenv.txt', fingerprint: false
            fingerprint 'fingerprint.txt'
        }
    }
}
