pipeline {
    agent {
        docker { image "vnstat/tools:latest" }
    }
    triggers {
        upstream 'Stage_from_GitHub'
    }
    stages {
        stage('Clean') {
            steps {
                sh 'rm -fr vnstat* *.txt *.xml'
            }
        }
        stage('Get') {
            steps {
                copyArtifacts(projectName: 'Stage_from_GitHub', filter: 'vnstat.tar.gz', selector: lastSuccessful())
                sh 'sha256sum vnstat.tar.gz >fingerprint.txt'
                sh 'tar zxvf vnstat.tar.gz'
                sh 'mv -v vnstat-* vnstat'
            }
        }
        stage('Cppcheck') {
            steps {
                sh '''
                   cppcheck --enable=all --xml --xml-version=2 -j4 \
                            --suppress=variableScope \
                            --suppress=knownConditionTrueFalse:vnstat/src/dbsql.c \
                            vnstat/src 2>cppcheck.xml
                '''
            }
        }
    }
    post {
        always {
            publishCppcheck pattern: 'cppcheck.xml'
            archiveArtifacts artifacts: 'fingerprint.txt, buildenv.txt', fingerprint: false
            fingerprint 'fingerprint.txt'
        }
    }
}
