pipeline {
    agent {
        docker { image "vnstat/debian:unstable" }
    }
    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10')
    }
    triggers {
        upstream 'Stage_from_GitHub'
    }
    stages {
        stage('Clean') {
            steps {
                sh 'rm -fr vnstat* *.txt coverage'
            }
        }
        stage('Get') {
            steps {
                copyArtifacts(projectName: 'Stage_from_GitHub', filter: 'vnstat.tar.gz', selector: lastSuccessful())
                sh 'sha256sum vnstat.tar.gz >fingerprint.txt'
                sh 'tar zxvf vnstat.tar.gz'
                sh 'mv -v vnstat-* vnstat'
            }
        }
        stage('Coverage') {
            steps {
                dir('vnstat') {
                    sh '''
                        ./configure
                        make profile
                        mv -v coverage ../
                    '''
                    script {
                        currentBuild.description = sh(script: 'sed -n -e \'s/^[0-9]*%: \\(Checks:[^,]*\\).*/\\1/p\' check_vnstat.log', returnStdout: true).trim()
                    }
                }
            }
        }
    }
    post {
        failure {
            sh 'cat vnstat/check_vnstat.log'
        }
        always {
            publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'coverage', reportFiles: 'index.html', reportName: 'Coverage Report', reportTitles: ''])
            archiveArtifacts artifacts: 'fingerprint.txt, vnstat/check_vnstat.log', fingerprint: false
            fingerprint 'fingerprint.txt'
        }
    }
}
