pipeline {
    agent any
    stages {
        stage('Setup') {
            steps {
                sh '''
                    rm -fr vnstat* *.txt *.gz
                    gcc --version >buildenv.txt

                    if [ ! -z "$LOCAL_FILE" ]; then
                        if [ ! -f "$LOCAL_FILE" ]; then
                            echo "Error: LOCAL_FILE \"$LOCAL_FILE\" doesn't exist"
                            exit 1
                        fi
                        echo "Using LOCAL_FILE \"$LOCAL_FILE\""
                        tar xvf "$LOCAL_FILE"
                        mv -v vnstat-* vnstat
                    fi
                '''
            }
        }
        stage('Checkout') {
            when {
                expression { params.LOCAL_FILE == '' }
            }
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/${BRANCH}']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'vnstat']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/vergoh/vnstat']]])
            }
        }
        stage('Test') {
            steps {
                dir('vnstat') {
                    sh '''
                        CFLAGS='-Wall -Wextra -g' ./configure
                        make check
                        cat check_vnstat.log
                    '''
                    script {
                        currentBuild.description = sh(script: 'sed -n -e \'s/^[0-9]*%: \\(Checks:[^,]*\\).*/\\1/p\' check_vnstat.log', returnStdout: true).trim()
                    }
                }
            }
        }
        stage('Package') {
            steps {
                dir('vnstat') {
                    sh '''
                        make dist
                        mv -v vnstat-*.gz ../vnstat.tar.gz
                        cd ..
                        sha256sum vnstat.tar.gz >fingerprint.txt
                    '''
                }
            }
        }
    }
    post {
        failure {
            sh 'cat vnstat/check_vnstat.log'
        }
        always {
            archiveArtifacts artifacts: 'vnstat.tar.gz, *.txt, vnstat/*.png, vnstat/check_vnstat.log', fingerprint: false
            fingerprint 'fingerprint.txt'
        }
    }
}
